CC      = gcc
CFLAGS  = -g
TARGET  = reverse

OBJS    = reverse.o

.SUFFIXES: .c .o

.DEFAULT_GOAL:  $(TARGET)

$(TARGET):      $(OBJS)
        $(CC) -o $@ $(OBJS)

.c.o:
        $(CC) $(CFLAGS) -c $<

PHONY: clean
clean:
        /bin/rm -f *.o $(TARGET)